# Generated by Django 5.2.6 on 2025-09-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price',
            new_name='rent',
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='facility',
            field=models.CharField(default='no facilities', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='floor_no',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='room_img',
            field=models.ImageField(blank=True, null=True, upload_to='room_images'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_size',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='room_view',
            field=models.CharField(default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='smoke',
            field=models.BooleanField(default=False),
        ),
    ]
