# Generated by Django 5.2.6 on 2025-09-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_rename_price_room_rent_room_bed_type_room_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(default='Double', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='facility',
            field=models.CharField(default='Wifi, Air-Conditioner, Breakfast, Restaurant, Swimming Pool', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_size',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
